# Generated by Django 5.2 on 2025-05-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cart", "0004_remove_cart_product_cartitem"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserCustom",
        ),
        migrations.AlterModelManagers(
            name="usercustom",
            managers=[],
        ),
    ]
