# Generated by Django 5.2 on 2025-05-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название категории",
                        max_length=150,
                        verbose_name="Название категории",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию продукта",
                        null=True,
                        upload_to="images/category/",
                        verbose_name="Изображение категории",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание категории",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название подкатегории",
                        max_length=150,
                        verbose_name="Название подкатегории",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию продукта",
                        null=True,
                        upload_to="images/subcategories/",
                        verbose_name="Изображение подкатегории",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание категории",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="catalog.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название продукта",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание продукта",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "image_small",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию продукта",
                        null=True,
                        upload_to="images/products/small/",
                        verbose_name="Изображение маленькое",
                    ),
                ),
                (
                    "image_medium",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию продукта",
                        null=True,
                        upload_to="images/products/medium/",
                        verbose_name="Изображение среднее",
                    ),
                ),
                (
                    "image_large",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию продукта",
                        null=True,
                        upload_to="images/products/large/",
                        verbose_name="Изображение большое",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        help_text="Введите цену продукта", verbose_name="Цена"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["title"],
            },
        ),
    ]
