# Generated by Django 5.2 on 2025-05-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["title"],
                "verbose_name": "Субкатегория",
                "verbose_name_plural": "Субкатегории",
            },
        ),
    ]
