# Generated by Django 5.2 on 2025-05-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                default="Описание недоступно",
                help_text="Введите описание категории",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="image_category",
                help_text="Загрузите фотографию продукта",
                upload_to="images/category/",
                verbose_name="Изображение категории",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="slug_category", unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                default="Описание недоступно",
                help_text="Введите описание продукта",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_large",
            field=models.ImageField(
                default="image_large_product",
                help_text="Загрузите фотографию продукта",
                upload_to="images/products/large/",
                verbose_name="Изображение большое",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_medium",
            field=models.ImageField(
                default="image_medium_product",
                help_text="Загрузите фотографию продукта",
                upload_to="images/products/medium/",
                verbose_name="Изображение среднее",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_small",
            field=models.ImageField(
                default="image_small_product",
                help_text="Загрузите фотографию продукта",
                upload_to="images/products/small/",
                verbose_name="Изображение маленькое",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="slug_product", unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="description",
            field=models.TextField(
                blank=True,
                default="Описание недоступно",
                help_text="Введите описание категории",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                default="image_subcategory",
                help_text="Загрузите фотографию продукта",
                upload_to="images/subcategories/",
                verbose_name="Изображение подкатегории",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(default="slug_subcategory", unique=True),
        ),
    ]
