# Generated by Django 5.2 on 2025-05-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_category_slug_alter_product_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                help_text="Загрузите фотографию продукта",
                upload_to="images/category/",
                verbose_name="Изображение категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_large",
            field=models.ImageField(
                help_text="Загрузите фотографию продукта",
                upload_to="images/products/large/",
                verbose_name="Изображение большое",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_medium",
            field=models.ImageField(
                help_text="Загрузите фотографию продукта",
                upload_to="images/products/medium/",
                verbose_name="Изображение среднее",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_small",
            field=models.ImageField(
                help_text="Загрузите фотографию продукта",
                upload_to="images/products/small/",
                verbose_name="Изображение маленькое",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                help_text="Загрузите фотографию продукта",
                upload_to="images/subcategories/",
                verbose_name="Изображение подкатегории",
            ),
        ),
    ]
